### PR TITLE
Changes to footprints

### PR DESCRIPTION
**Pull request by electron271**

### CODE REVIEW

**Comment by electron271** [comment]
TODO:

- [ ] Add symbol for Pins_2x05_2.54mm_TH_EuroPower_Shrouded
- [ ] Make EuroPower footprints more simple and readable
- [ ] Horizontal Barrel Jack footprint
- [ ] Try to add components from https://docs.google.com/spreadsheets/d/1iTYuDH9-MzQPRmAlmlgo6OXsGFgu6emcyYLw7d7ScM0/edit?usp=sharing

**Comment by electron271** [comment]
**DO NOT MERGE UNTIL ALL TASKS ARE COMPLETED**

**Comment by electron271** [comment]
@danngreen @dongero I know that your busy working on 4ms and other things, but I need a bit of help having everything work with 4ms

**Comment by danngreen** [comment]
What kind of help do you need? I won't have a chance to review the changes in this PR until Monday

**Comment by electron271** [comment]
I need some part numbers to be assigned, I'll try also to do that. I'll give you a quick summary on the changes:
image
EuroPower Shrouded 5-pins added
image
Better 8-pin europower shrouded footprint
image
Common Barrel Jack Horizontal footprint added

**Comment by electron271** [comment]
Also made the appropriate symbol for the 5-pin shrouded EuroPower

**Comment by danngreen** [comment]
Those look nice, I'll check them over tomorrow and add P/N if you haven't already when I'm back in the office.

**Comment by electron271** [comment]
Thanks!

**Comment by electron271** [comment]
@danngreen I can't set the part number (on my laptop), but I think Mouser 710-61201021621 should work, it has about 43k in stock

**Comment by electron271** [comment]
https://www.mouser.com/ProductDetail/CUI-Devices/PJ-202A?qs=WyjlAZoYn50aq4XmSpZ3Rg%3D%3D This seems to be the barrel jack

**Comment by danngreen** [comment]
I'm looking at the 2x08 and 2x05 shrouded pin header right now. Looks good except for one thing:
All the other headers in the 4ms_Connectors library have the origin at the center of the footprint, while these two have the origin at pin 1. This is a place where we break from the Kicad Library Convention, which dictates that the origin be at pin 1 ([KLC 7.2](https://klc.kicad.org/footprint/f7/f7.2/)).
We do it this way because rotating and flipping headers, especially aligning header/socket pairs on multi-board designs, is less error-prone and easier when the footprint is center-aligned.

Do you mind making that adjustment?

We definitely need to document our own Library Convention (or at least the few places we break from KLC), I'll create an issue for it.

**Comment by electron271** [comment]
No problem I'm getting on my computer in a few minutes

**Comment by electron271** [comment]
@danngreen Done! Let me see if I can assign the P/N for the Barrel Jack and 5-pin conn, but I don't know what to use for the 8-pin conn

**Comment by electron271** [comment]
Actually, I'll just use the old part number you used for the 8-pin conn, and for the barrel jack leave it unassigned, as there are hundreds of different models that use the same footprint, and some people prefer one over another

**Comment by electron271** [comment]
Do I need to assign it to just the symbols, or also the footprints?

**Comment by danngreen** [comment]
Only symbols get part numbers. 
Another thing I should document is our custom fields for symbols:
`Part Number`
`Manufacturer`

then optionally:
`Part Number 2`
`Manufacturer 2`
and more...

We also have `Specifications` as a custom field for all symbols

**Comment by danngreen** [comment]
The 10-pin shrouded symbol should be centered around the origin (this one is in line with the KLC).

Oh, I notice that the unshrouded 10-pin header is not properly centered, that's an error too.

**Comment by danngreen** [comment]
Screen Shot 2022-06-13 at 1 12 43 PM

Also, the Keywords field should say Shrouded

**Comment by danngreen** [comment]
Regarding the horizontal barrel jack, we should have a part number included in the symbol because there's already a similar symbol in the library that has a different pinout: `4ms_Jack:Barrel_RtAngle_PJ066`

Screen Shot 2022-06-13 at 1 17 55 PM

**Comment by danngreen** [comment]
Perhaps we need to put the pinout in the symbol or footprint? I'm not sure the best approach here.

**Comment by danngreen** [comment]
Actually... I think the PJ066 footprint has a faulty pinout. The [datasheet](https://www.cuidevices.com/product/resource/pj-066a.pdf) indicates
Screen Shot 2022-06-13 at 1 23 25 PM

I need to look at it again, but I think the one you created is correct, and the old one is wrong.

**Comment by electron271** [comment]
Actually, that one is from KiCAD, Let me edit it a little

**Comment by electron271** [comment]
Alright, let me add those changes

**Comment by danngreen** [comment]
I'm a bit confused by own my footprint `4ms_Jack:Barrel_RtAngle_PJ066`. I need to dig out some old prototype boards where I used it to get to the bottom of this. In any case, we can ignore it for the moment

**Comment by electron271** [comment]
image
Is this good?

**Comment by danngreen** [comment]
The text by the pins is helpful.

Since the dimensions match the PJ202A, let's make a symbol for this exact part. I hear you that there are many different compatible part numbers, but having at least one with the datasheet link will be useful in determining what parts might be compatible. The pinout is pretty generic, but the physical dimensions aren't so much.

Let's keep the Barrel_RtAngle_PJ066 in the library for now (it was deleted in your last commit). I need to make a symbol for it as well. I'll do that.

**Comment by electron271** [comment]
Alright, I re-added the old barrel jack footprint

**Comment by electron271** [comment]
@danngreen May I ask how the symbol is going?

**Comment by danngreen** [comment]
Multi-tasking a few things right now... I won't be able to do the PJ066A symbol today, but I can make a PJ202A symbol easily right now.

Ok, I think we should name the footprint Barrel_Horizontal_PJ202, in line with the other Barrel jacks in the Jack library (`Barrel_RtAngle_PJ066`, `Barrel_Vert_PJ064`)

**Comment by electron271** [comment]
Alrighty

**Comment by danngreen** [comment]
Allright, actually if you can rename the footprint to `Barrel_Horizontal_PJ202`, I can merge this in. Then I'll add the symbol for that part on the master branch. I think that's easier than trying to merge my changes into your PR

**Comment by electron271** [comment]
Alright

**Comment by electron271** [comment]
Can't wait to hopefully see my work in a 4ms module!

**Comment by danngreen** [comment]
Looks good! Thanks for helping cleanup all the picky little things!

**Comment by electron271** [comment]
No problem! Always happy to help the Eurorack and Synthesizer community!

**Comment by danngreen** [comment]
Awesome! I pushed the symbol too. I still need to verify the PJ-066A footprint, but everything in your PR is tidied up

**Pull request merged**
